// <auto-generated />
using System;
using Hms.ReceptionApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Hms.ReceptionApi.Migrations
{
    [DbContext(typeof(ReceptionDbContext))]
    partial class ReceptionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Hms.ReceptionApi.Entities.PatientCheckIn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CheckInTimeUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
<<<<<<< HEAD
                        .HasColumnType("datetime2");
=======
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");
>>>>>>> ee49ab9fb4705d2037d437f343847efd9ce49e85

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
<<<<<<< HEAD
                        .HasColumnType("bit");
=======
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);
>>>>>>> ee49ab9fb4705d2037d437f343847efd9ce49e85

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TokenNumber")
                        .HasColumnType("int");

                    b.Property<string>("UHID")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

<<<<<<< HEAD
=======
                    b.HasIndex("DepartmentId");

                    b.HasIndex("DoctorId");

>>>>>>> ee49ab9fb4705d2037d437f343847efd9ce49e85
                    b.HasIndex("PatientId");

                    b.HasIndex("DepartmentId", "CheckInTimeUtc");

<<<<<<< HEAD
=======
                    b.HasIndex("PatientId", "AppointmentId")
                        .IsUnique();

>>>>>>> ee49ab9fb4705d2037d437f343847efd9ce49e85
                    b.ToTable("PatientCheckIns", (string)null);
                });

            modelBuilder.Entity("Hms.ReceptionApi.Entities.QueueToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CalledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CancelledAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAtUtc")
<<<<<<< HEAD
                        .HasColumnType("datetime2");
=======
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETUTCDATE()");
>>>>>>> ee49ab9fb4705d2037d437f343847efd9ce49e85

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
<<<<<<< HEAD
                        .HasColumnType("bit");
=======
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);
>>>>>>> ee49ab9fb4705d2037d437f343847efd9ce49e85

                    b.Property<string>("Notes")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
<<<<<<< HEAD
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");
=======
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");
>>>>>>> ee49ab9fb4705d2037d437f343847efd9ce49e85

                    b.Property<DateOnly>("QueueDate")
                        .HasColumnType("date");

                    b.Property<DateTime?>("SkippedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("StartedAtUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("TokenNumber")
                        .HasColumnType("int");

                    b.Property<string>("UHID")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("UpdatedAtUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

<<<<<<< HEAD
=======
                    b.HasIndex("AppointmentId");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.HasIndex("DepartmentId", "QueueDate", "Status");

>>>>>>> ee49ab9fb4705d2037d437f343847efd9ce49e85
                    b.HasIndex("DepartmentId", "QueueDate", "TokenNumber")
                        .IsUnique();

                    b.ToTable("QueueTokens", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
