// <auto-generated />
using System;
using Hms.AuthApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace Hms.AuthApi.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    partial class AuthDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            // 🔹 ROLE ENTITY (CORRECT SEED DATA)
            modelBuilder.Entity("Hms.AuthApi.Entities.Role", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd();
                b.Property<string>("Name").IsRequired().HasMaxLength(50);
                b.Property<string>("NormalizedName").IsRequired().HasMaxLength(50);
                b.Property<bool>("IsDeleted");
                b.Property<DateTime>("CreatedAtUtc");
                b.Property<DateTime?>("UpdatedAtUtc");

                b.HasKey("Id");
                b.HasIndex("Name").IsUnique();
                b.HasIndex("NormalizedName").IsUnique();

                b.ToTable("Roles");

                b.HasData(
                    new { Id = 1, Name = "Admin", NormalizedName = "ADMIN", IsDeleted = false, CreatedAtUtc = new DateTime(2026, 5, 1, 9, 22, 20, DateTimeKind.Utc) },
                    new { Id = 2, Name = "Patient", NormalizedName = "PATIENT", IsDeleted = false, CreatedAtUtc = new DateTime(2026, 5, 1, 9, 22, 20, DateTimeKind.Utc) },
                    new { Id = 3, Name = "Doctor", NormalizedName = "DOCTOR", IsDeleted = false, CreatedAtUtc = new DateTime(2026, 5, 1, 9, 22, 20, DateTimeKind.Utc) },
                    new { Id = 4, Name = "Receptionist", NormalizedName = "RECEPTIONIST", IsDeleted = false, CreatedAtUtc = new DateTime(2026, 5, 1, 9, 22, 20, DateTimeKind.Utc) }
                );
            });

            // 🔹 USER ENTITY
            modelBuilder.Entity("Hms.AuthApi.Entities.User", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd();
                b.Property<string>("MobileNumber").IsRequired().HasMaxLength(20);
                b.Property<string>("Email").HasMaxLength(150);
                b.Property<string>("LoginId").HasMaxLength(100);
                b.Property<string>("PasswordHash").HasMaxLength(500);
                b.Property<string>("PhotoUrl").HasMaxLength(500);

                b.Property<bool>("IsActive").HasDefaultValue(true);
                b.Property<bool>("IsDeleted");
                b.Property<bool>("IsFirstLoginCompleted").HasDefaultValue(false);
                b.Property<bool>("IsOtpLoginEnabled").HasDefaultValue(true);
                b.Property<bool>("IsPasswordLoginEnabled").HasDefaultValue(false);

                b.Property<DateTime>("CreatedAtUtc");
                b.Property<DateTime?>("UpdatedAtUtc");

                b.HasKey("Id");
                b.HasIndex("LoginId").IsUnique().HasFilter("[LoginId] IS NOT NULL");
                b.HasIndex("MobileNumber");

                b.ToTable("Users");
            });

            // 🔹 STAFF USER (FIXED)
            modelBuilder.Entity("Hms.AuthApi.Entities.StaffUser", b =>
            {
                b.Property<int>("Id").ValueGeneratedOnAdd();
                b.Property<int>("UserId");
                b.Property<string>("FullName").IsRequired().HasMaxLength(150);

                b.Property<bool>("IsDeleted");
                b.Property<DateTime>("CreatedAtUtc");
                b.Property<DateTime?>("UpdatedAtUtc");

                b.HasKey("Id");
                b.HasIndex("UserId").IsUnique();

                b.ToTable("StaffUsers");

                b.HasOne("Hms.AuthApi.Entities.User", "User")
                    .WithOne("StaffUser")
                    .HasForeignKey("Hms.AuthApi.Entities.StaffUser", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

            // 🔹 USER ROLE
            modelBuilder.Entity("Hms.AuthApi.Entities.UserRole", b =>
            {
                b.Property<int>("UserId");
                b.Property<int>("RoleId");

                b.Property<int>("Id");
                b.Property<bool>("IsDeleted");
                b.Property<DateTime>("CreatedAtUtc");
                b.Property<DateTime?>("UpdatedAtUtc");

                b.HasKey("UserId", "RoleId");
                b.HasIndex("RoleId");

                b.ToTable("UserRoles");

                b.HasOne("Hms.AuthApi.Entities.Role", "Role")
                    .WithMany("UserRoles")
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired();

                b.HasOne("Hms.AuthApi.Entities.User", "User")
                    .WithMany("UserRoles")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();
            });
        }
    }
}